# Generated by Django 4.2.14 on 2024-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_gardentip_region_alter_gardentip_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardentip',
            name='region',
            field=models.CharField(choices=[('SE', 'SOUTHERN ENGLAND'), ('WE', 'WESTERN ENGLAND'), ('WA', 'WALES'), ('NE', 'NORTEHRN ENGLAND'), ('SC', 'SCOTLAND'), ('NI', 'NORTHERN IRELAND'), ('MI', 'MIDLANDS')], default='SE'),
        ),
        migrations.AlterField(
            model_name='gardentip',
            name='season',
            field=models.CharField(choices=[('spring', 'SPRING'), ('summer', 'SUMMER'), ('autumn', 'AUTUMN'), ('winter', 'WINTER')], default='summer'),
        ),
    ]
