# Generated by Django 4.2.14 on 2024-07-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='gardentip',
            options={'ordering': ['-created_on']},
        ),
    ]
