# Generated by Django 4.2.14 on 2024-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_alter_gardentip_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardentip',
            name='region',
            field=models.CharField(choices=[('Southern England', 'SOUTHERN ENGLAND'), ('West of England', 'WESTERN ENGLAND'), ('Wales', 'WALES'), ('North of England', 'NORTEHRN ENGLAND'), ('Scotland', 'SCOTLAND'), ('Northern Ireland', 'NORTHERN IRELAND'), ('Midlands', 'MIDLANDS'), ('Outside the UK', 'NON UK')], default='SE'),
        ),
    ]
