# Generated by Django 4.2.14 on 2024-08-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_alter_gardentip_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='garden_tip',
            new_name='post',
        ),
    ]
