# Generated by Django 4.2.14 on 2024-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_rename_garden_tip_feedback_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(choices=[(' ', 'Score 0 out of 5'), ('*', 'Score 1 out of 5'), ('**', 'Score 2 out of 5'), ('***', 'Score 3 out of 5'), ('****', 'Score 4 out of 5'), ('*****', 'Score 5 out of 5')], default=' '),
        ),
    ]
