# Generated by Django 4.2.14 on 2024-08-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_alter_feedback_options_alter_feedback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardentip',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
