# Generated by Django 4.2.14 on 2024-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_gardentip_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardentip',
            name='approved',
        ),
    ]
