# Generated by Django 4.2.14 on 2024-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_remove_gardentip_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(choices=[(' ', 'Score 0 out of 5'), ('*', 'Score 1 out of 5'), ('**', 'Score 2 out of 5'), ('***', 'Score 3 out of 5'), ('****', 'Score 4 out of 5'), ('*****', 'Score 5 out of 5')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='gardentip',
            name='region',
            field=models.CharField(choices=[('Southern England', 'SOUTHERN ENGLAND'), ('West of England', 'WESTERN ENGLAND'), ('Wales', 'WALES'), ('North of England', 'NORTEHRN ENGLAND'), ('Scotland', 'SCOTLAND'), ('Northern Ireland', 'NORTHERN IRELAND'), ('Midlands', 'MIDLANDS'), ('Outside the UK', 'NON UK')], default='SE', max_length=50),
        ),
        migrations.AlterField(
            model_name='gardentip',
            name='season',
            field=models.CharField(choices=[('Spring', 'SPRING'), ('Summer', 'SUMMER'), ('Autumn', 'AUTUMN'), ('Winter', 'WINTER')], default='summer', max_length=50),
        ),
    ]
